# Generated by Django 5.0.6 on 2024-07-24 00:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True, verbose_name='user email')),
                ('username', models.CharField(max_length=50, verbose_name='user name')),
                ('document', models.CharField(max_length=50, unique=True, verbose_name='CPF')),
                ('phone_number', models.CharField(max_length=20, verbose_name='phone number')),
                ('first_name', models.CharField(max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last name')),
                ('street', models.CharField(max_length=100, verbose_name='andress street')),
                ('number', models.CharField(max_length=20, verbose_name='andress house number')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='andress neighborhood')),
                ('city', models.CharField(max_length=100, verbose_name='andress city')),
                ('state', models.CharField(max_length=100, verbose_name='andress state')),
                ('zip_code', models.CharField(max_length=10, verbose_name='andress zip code')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'user',
            },
        ),
    ]
