# Generated by Django 5.0.6 on 2024-07-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_usermodel_groups_usermodel_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='created_at',
            field=models.DateField(auto_now_add=True, default='2024-03-01'),
            preserve_default=False,
        ),
    ]
