# Generated by Django 5.0.6 on 2024-07-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_usermodel_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='username',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Cidade'),
        ),
    ]
