# Generated by Django 5.0.6 on 2024-07-29 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_usermodel_username_alter_usermodel_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoookModel',
        ),
    ]
