# Generated by Django 5.0.6 on 2024-08-06 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_delete_boookmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Pontos'),
        ),
    ]
