# Generated by Django 5.0.6 on 2024-08-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_usermodel_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='points',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='Pontos'),
        ),
    ]
