# Generated by Django 5.0.6 on 2024-08-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_usermodel_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='neighborhood',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='district',
            field=models.CharField(default='teste', max_length=100, verbose_name='Bairro'),
        ),
    ]
