# Generated by Django 5.0.6 on 2024-08-19 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_usermodel_neighborhood_usermodel_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=50, verbose_name='password'),
        ),
    ]
