# Generated by Django 5.0.6 on 2024-08-24 16:31

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_usermodel_groups_usermodel_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='points',
            field=models.DecimalField(decimal_places=2, default=Decimal('100'), max_digits=6, verbose_name='Pontos'),
        ),
    ]
