# Generated by Django 5.0.6 on 2024-08-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_usermodel_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='latitude',
            field=models.FloatField(default=-23.55052, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='longitude',
            field=models.FloatField(default=-46.633308, verbose_name='longitude'),
        ),
    ]
