# Generated by Django 5.0.6 on 2024-09-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_usermodel_latitude_alter_usermodel_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=100, verbose_name='password'),
        ),
    ]
