# Generated by Django 5.0.6 on 2024-09-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_usermodel_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='last_login',
            field=models.DateField(default='2024-09-06', verbose_name='last_login'),
            preserve_default=False,
        ),
    ]
