# Generated by Django 5.0.6 on 2024-10-07 17:47

import django.core.validators
import main.models.user_model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_usermodel_image_alter_usermodel_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='image',
            field=models.ImageField(blank=True, default=main.models.user_model.get_user_avatar_random, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])]),
        ),
    ]
