# Generated by Django 5.0.6 on 2024-07-26 18:51

import book.models.book_model
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100, verbose_name='título')),
                ('author', models.CharField(max_length=100, verbose_name='autor')),
                ('version', models.CharField(max_length=50, verbose_name='edição')),
                ('published_at', models.CharField(verbose_name='data de publicação')),
                ('description', models.TextField(max_length=255, verbose_name='descricao')),
                ('image', models.ImageField(blank=True, null=True, upload_to=book.models.book_model.get_upload_path_image)),
                ('available', models.BooleanField(default=True, verbose_name='disponibilidade')),
                ('posted_at', models.DateField(auto_now_add=True, verbose_name='data de postagem')),
                ('rating', models.FloatField(verbose_name='nota média')),
                ('g_api_id', models.CharField(max_length=50, verbose_name='google api id')),
                ('g_api_tag', models.CharField(max_length=50, verbose_name='google api tag')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to=settings.AUTH_USER_MODEL, verbose_name='book')),
            ],
        ),
    ]
