# Generated by Django 5.0.6 on 2024-07-26 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmodel',
            options={'verbose_name': 'book', 'verbose_name_plural': 'books'},
        ),
        migrations.AlterModelTable(
            name='bookmodel',
            table='book',
        ),
    ]
