# Generated by Django 5.0.6 on 2024-07-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_bookmodel_options_alter_bookmodel_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='g_api_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='google api id'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='g_api_tag',
            field=models.CharField(blank=True, max_length=50, verbose_name='google api tag'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='rating',
            field=models.FloatField(blank=True, verbose_name='nota média'),
        ),
    ]
