# Generated by Django 5.0.6 on 2024-07-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_remove_bookmodel_author_remove_bookmodel_g_api_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='authors',
            field=models.CharField(max_length=100, verbose_name='autor'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='language',
            field=models.CharField(max_length=5, verbose_name='idioma'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='total_pages',
            field=models.IntegerField(verbose_name='número de paginas'),
        ),
    ]
