# Generated by Django 5.0.6 on 2024-07-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_remove_bookmodel_posted_at_bookmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
