# Generated by Django 5.0.6 on 2024-07-31 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_alter_bookmodel_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='description',
            field=models.TextField(max_length=10000, verbose_name='descricao'),
        ),
    ]
