# Generated by Django 5.0.6 on 2024-07-31 14:15

import book.models.book_model
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_alter_bookmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=book.models.book_model.get_upload_path_image, validators=[django.core.validators.FileExtensionValidator(['png', 'jpeg', 'jpg'])]),
        ),
    ]
