# Generated by Django 5.0.6 on 2024-08-02 18:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='nota')),
                ('body', models.TextField(verbose_name='Comentário')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='book.bookmodel', verbose_name='post')),
            ],
            options={
                'verbose_name': 'avaliacao',
                'verbose_name_plural': 'avaliacoes',
                'db_table': 'avaliacao',
            },
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
