# Generated by Django 5.0.6 on 2024-08-02 23:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_avaliationmodel_delete_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliationmodel',
            name='name',
        ),
        migrations.AddField(
            model_name='avaliationmodel',
            name='title',
            field=models.CharField(default='e', max_length=50, verbose_name='titulo'),
        ),
        migrations.AddField(
            model_name='avaliationmodel',
            name='user',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
    ]
