# Generated by Django 5.0.6 on 2024-08-03 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0020_categorymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='category',
            field=models.ForeignKey(default='57c6e24d-a824-491d-8df6-2def8e9d0d65', on_delete=django.db.models.deletion.CASCADE, related_name='category', to='book.categorymodel', verbose_name='categoria'),
        ),
    ]
