# Generated by Django 5.0.6 on 2024-08-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0021_bookmodel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='book_api_tag',
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='book_api_etag',
            field=models.CharField(blank=True, max_length=50, verbose_name='google api tag'),
        ),
    ]
