# Generated by Django 5.0.6 on 2024-08-06 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0022_remove_bookmodel_book_api_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='book.categorymodel', verbose_name='categoria'),
        ),
    ]
