# Generated by Django 5.0.6 on 2024-08-19 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0023_alter_bookmodel_category'),
        ('main', '0013_remove_usermodel_groups_remove_usermodel_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliationmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_avaliations', to='main.usermodel', verbose_name='usuario'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='main.usermodel', verbose_name='book'),
        ),
    ]
