# Generated by Django 5.0.6 on 2024-08-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0024_alter_avaliationmodel_user_alter_bookmodel_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=100, max_digits=5, null=True, verbose_name='preço'),
        ),
    ]
