# Generated by Django 5.0.6 on 2024-08-07 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0023_alter_bookmodel_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeModel',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('BT', 'Trocar por outro livro'), ('PT', 'Trocar por pontos')])),
                ('shipping_method', models.CharField(choices=[('CR', 'Correios')])),
                ('status', models.BooleanField(default=False, verbose_name='status')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trade', to='book.bookmodel', verbose_name='livro')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
        ),
    ]
