# Generated by Django 5.0.6 on 2024-08-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trademodel',
            options={'verbose_name': 'trade', 'verbose_name_plural': 'trades'},
        ),
        migrations.AlterField(
            model_name='trademodel',
            name='payment_method',
            field=models.CharField(choices=[('BT', 'Trocar por um de seus livros'), ('PT', 'Trocar por pontos')], verbose_name='Método de pagamento'),
        ),
        migrations.AlterField(
            model_name='trademodel',
            name='shipping_method',
            field=models.CharField(choices=[('CR', 'Correios')], verbose_name='Método de envio'),
        ),
        migrations.AlterModelTable(
            name='trademodel',
            table='trades',
        ),
    ]
