# Generated by Django 5.0.6 on 2024-08-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_alter_trademodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trademodel',
            name='shipping_method',
            field=models.CharField(blank=True, choices=[('CR', 'Correios')], null=True, verbose_name='Método de envio'),
        ),
    ]
