# Generated by Django 5.0.6 on 2024-08-10 15:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_alter_trademodel_shipping_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trademodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
