# Generated by Django 5.0.6 on 2024-08-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_alter_trademodel_book_alter_trademodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trademodel',
            old_name='status',
            new_name='accepted',
        ),
        migrations.AddField(
            model_name='trademodel',
            name='finalizate',
            field=models.BooleanField(default=False, verbose_name='finalizado'),
        ),
    ]
