# Generated by Django 5.0.6 on 2024-08-19 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_remove_usermodel_groups_remove_usermodel_last_login_and_more'),
        ('trade', '0006_rename_status_trademodel_accepted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trademodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='main.usermodel', verbose_name='usuário'),
        ),
    ]
