# Generated by Django 5.0.6 on 2024-08-22 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0024_alter_avaliationmodel_user_alter_bookmodel_owner'),
        ('trade', '0007_alter_trademodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trademodel',
            name='book_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='book.bookmodel', verbose_name='livro ofertado'),
        ),
        migrations.AddField(
            model_name='trademodel',
            name='points_offer',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='pontos ofertados'),
            preserve_default=False,
        ),
    ]
