# Generated by Django 5.0.6 on 2024-08-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0008_trademodel_book_offer_trademodel_points_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trademodel',
            name='points_offer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='pontos ofertados'),
        ),
    ]
