# Generated by Django 5.0.6 on 2024-08-24 16:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0009_alter_trademodel_points_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trademodel',
            name='points_offer',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('100'), max_digits=6, null=True, verbose_name='pontos ofertados'),
        ),
    ]
