# Generated by Django 5.0.6 on 2024-08-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0010_alter_trademodel_points_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='trademodel',
            name='first_ship',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Primeiro envio'),
        ),
    ]
