# Generated by Django 5.0.6 on 2024-08-27 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0011_trademodel_first_ship'),
    ]

    operations = [
        migrations.AddField(
            model_name='trademodel',
            name='owner_shipping_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código de envio do propietário'),
        ),
        migrations.AddField(
            model_name='trademodel',
            name='user_shipping_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Código de envio do requisitante'),
        ),
    ]
