# Generated by Django 5.0.6 on 2024-09-02 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0012_trademodel_owner_shipping_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trademodel',
            name='status',
            field=models.CharField(choices=[('OP', 'Aberta'), ('AC', 'Aceita'), ('FS', 'Primeiro envio'), ('FN', 'Finalizada')], default='OP', max_length=2),
        ),
    ]
