# Generated by Django 5.0.6 on 2024-09-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0013_trademodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trademodel',
            name='owner_shipping_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código de envio do propietário'),
        ),
        migrations.AlterField(
            model_name='trademodel',
            name='user_shipping_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código de envio do requisitante'),
        ),
    ]
